---
title: "Melissa Data"
output: html_notebook
---

```{r}
library(data.table)
library(CATALYST)
path_to_data <- "/Users/judithbernett/Downloads/Cyanus_RPsMPs/"
panel <- fread(paste0(path_to_data, "panel.csv"))
md <- fread(paste0(path_to_data, "metafile RP MP all.csv"))
sce <- prepData(paste0(path_to_data, "files"), 
                panel, 
                md, 
                md_cols = list(file = "file_name", id = "sample_id", factors = c("activation", "patient_id", "subgroup", "subgroup2")))
```

Diagnostic Plot: subgroup2
```{r}
plotExprs(sce, color_by = "subgroup2")
```

```{r}
library(ggplot2)

exprsData <- assays(sce)$exprs
exprsData <- data.frame(t(exprsData), colData(sce), check.names = FALSE)
gg_df <- reshape2::melt(exprsData, value.name = "expression", variable.name = "marker", id.vars = names(colData(sce)))
gg_df <- as.data.table(gg_df)
ggplot(gg_df[marker == "CD42b"], fill = NULL, aes_string(x = "expression", y = "..ndensity..", col = "activation", group = "sample_id")) +
  facet_wrap(subgroup2~marker, scales = "free_x") + 
  geom_density()

```

compute factors
```{r}
medians <- merge(gg_df[marker == "CD42b" & subgroup2 == "RP", median(expression), by="patient_id"], gg_df[marker == "CD42b" & subgroup2 == "MP", median(expression), by="patient_id"], by="patient_id")
colnames(medians) <- c("patient_id", "RP_median", "MP_median")
medians[, foldchange := RP_median/MP_median]

overall_median <- gg_df[marker == "CD42b" & subgroup2 =="RP", median(expression)] / gg_df[marker == "CD42b" & subgroup2 =="MP", median(expression)]

gg_df_merged <- merge(gg_df, medians[, c("patient_id", "foldchange")], by="patient_id")
```

correction
```{r}
gg_df_merged[, expression_mod := ifelse(subgroup2 == "MP", expression * foldchange, expression)]
ggplot(gg_df_merged, fill = NULL, aes_string(x = "expression_mod", y = "..ndensity..", col = "subgroup2", group = "sample_id")) +
  facet_wrap(~marker, scales = "free_x") + 
  geom_density() 
```

patient-specific foldchanges per marker
```{r}
medians <- merge(gg_df[subgroup2 == "RP", median(expression), by=c("marker", "patient_id")], gg_df[subgroup2 == "MP", median(expression), by=c("marker", "patient_id")], by=c("marker", "patient_id"))
colnames(medians) <- c("marker", "patient_id", "RP_median", "MP_median")
medians[, foldchange := RP_median/MP_median]

ggplot(medians[marker != "CD40"], aes(x = reorder(marker, foldchange), y = foldchange))+
  geom_boxplot()+
  geom_jitter(aes(shape=patient_id, color = patient_id))+
  scale_shape_manual(values=1:nlevels(medians$patient_id))
```

